.\" Manpage for hardinfo.
.\" https://github.com/hwspeedy/hardinfo2/.
.TH HARDINFO "1" "May 2025" "2.2" "User Commands"
.SH NAME
\fBHardinfo2\fR \- System Information and Benchmark for Linux Systems.
.SH USAGE
\fBhardinfo2\fR [OPTION...]
.SH DESCRIPTION
Is a system information and benchmark for Linux systems, that gathers information about the 
hardware and operating system, performs benchmarks with online compare against other machines, and generates reports.

Online Userguide with more info: https://hardinfo2.org/userguide

.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Show help options
.TP
\fB\-q\fR, \fB\-\-quiet\fR
do not print status messages to standard output
.TP
\fB\-r\fR, \fB\-\-generate\-report\fR
creates a report and prints to standard output
.TP
\fB\-f\fR, \fB\-\-report\-format\fR
chooses a report format (text, html)
.TP
\fB\-t\fR, \fB\-\-topic\fR
search for a topic in CLI report (-t getlist shows available)
.TP
\fB\-c\fR, \fB\-\-topic-cache\fR
search for a topic in Cached CLI report (-t getlist shows available)
.TP
\fB\-b\fR, \fB\-\-run\-benchmark\fR
run a specific benchmark eg. -b 'FPU FFT'  (Default all benchmarks runs when generate report)
.TP
\fB\-u\fR, \fB\-\-user\-note Group-MachineName[-ServerReq]\fR
adds a user note to data send to server. When added eg. -u 1 synchronization is activated.
Letters (small+caps) and numbers and dashes are accepted. Length max 50. 0-2 dashes used as seperator.
Format Group-MachineName-ServerReq
Group and MachineName are for anonymous identification and can put benchmarks into a group and you can sort of identify each machine by your chosen string.
ServerReq is to tell the server which records you want to get. See https://hardinfo2.org/userguide#usernote for more details about the Server Request strings available.
.TP
\fB\-g\fR, \fB\-\-result\-format\fR
chooses a result format (short, conf, shell)
.TP
\fB\-n\fR, \fB\-\-max\-results\fR
maximum number of benchmark results to include (-1 for no limit, default is 50)
.TP
\fB\-v\fR, \fB\-\-version\fR
shows program version and quit
.TP
\fB\-s\fR, \fB\-\-skip\-benchmark\fR
Disables all benchmark runs.
.TP
\fB\-w\fR, \fB\-\-very\-verbose\fR
show all details
.SH EXAMPLES
examples of CLI command usage:\fR
.TP
hardinfo2 -b 'FPU FFT'
runs only FPU FFT benchmark
.TP
hardinfo2 -u 1
enable updates at startup and starts gui (can also be set in gui)
.TP
hardinfo2 -u choosengroup-choosenid -r
Updates data from server, generate CLI report and sends benchmark with user-note. See more at https://hardinfo2.org/userguide#usernote
.TP
hardinfo2 -r
generates CLI report

.SH COPYRIGHT
\fBHardinfo2\fR is Copyright \(co 2003-2023 L. A. F. Pereira, 2024- Hardinfo2 Project\fR.
This is free software; see the source for copying conditions.  There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
